sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          input_type: text
          type: text
          listable: hidden
          display: Titre
      -
        handle: description
        field:
          type: textarea
          listable: hidden
          display: Description
      -
        handle: footer
        field:
          restrict: false
          automatic_line_breaks: true
          automatic_links: false
          escape_markup: false
          smartypants: false
          type: markdown
          listable: hidden
          display: Footer
      -
        handle: analytics
        field:
          theme: material
          mode: htmlmixed
          indent_type: tabs
          indent_size: 4
          key_map: default
          line_numbers: true
          line_wrapping: true
          type: code
          listable: hidden
          display: Analytics
